- internal/sinkcores/sentrycore/worker.go
Right now, error messages are super non-descript because most context is in the _log_ message, not in the error message. I think it's useful to have the log message here because it also matters _where_ each error is being reported from, so grouping by log messages is something we probably want.
And of course we add the scope, because we want those to become important keys in navigating observability reports.
> sentrycore: wrap error with log message

- init.go
- internal/configurable/logger.go
- internal/configurable/logger_test.go
- internal/sinkcores/sentrycore/benchmarks/bench_test.go
- internal/sinkcores/sentrycore/integration_test.go
- logger.go
- logtest/logtest.go
- sinks.go
- sinks_sentry.go
Was looking to have [an answer to this Slack question documented in the package docs](https://sourcegraph.slack.com/archives/C01N83PS4TU/p1654903757077709), and noticed a variety of improvements we could make to improve the readability of our [package docs](https://pkg.go.dev/github.com/sourcegraph/log):
- `Sink` has many exported functions that do not need to be exported, so we make `build` and `update` private to reduce the documentation here. This also prevents package users from building their own implementations, which we can't guarantee the behaviour of
- `Sinks` does not need to be used directly, so we make it private, which also nicely removes all the exports of `zapcore.Core`
- There are usages of `Sinks` in testing that can be replaced with using the private `WithCore` hook, so …
> sinks: document and reduce public API surface

- logtest/logtest.go
We init liberally in logtest for a more seamless experience, but the init hook inside logtest also reaches into standard test library setup that is not thread-safe, leading to race conditions:
https://buildkite.com/sourcegraph/sourcegraph/builds/155034#01816c05-1bbd-4041-a362-e7caeb8af6a8/6-3302
```
\| WARNING: DATA RACE
--
  | \| Read at 0x00c0000c0138 by goroutine 88:
  | \|   flag.(*FlagSet).Parsed()
... truncated ...
\|   flag.Parse()
--
  | \|       /root/.asdf/installs/golang/1.18.1/go/src/flag/flag.go:1036 +0xcf
  | \|   github.com/sourcegraph/log/logtest.Init()
  | \|       /root/.asdf/installs/golang/1.18.1/packages/pkg/mod/github.com/sourcegraph/log@v0.0.0-20220613150728-bb50c87ba841/logtest/logtest.go:28 +0x3b
  | \|   github.com/sourcegraph/log/logtest.scopedTestLogger()
  | …
```
> logtest: init only once

- internal/sinkcores/sentrycore/integration_test.go
I was going over the `quality-of-life` label in sg/sg, seeing if we closed issues with the recent Sentry work and noticed a ticket about traces (https://github.com/sourcegraph/sourcegraph/issues/17751) . It was working out of the box, but due to the importance of such a feature, a test should cover any possible regression.
> Add a test case to cover export traceIds in Sentry

- fields.go
Adds `Binary` (reqeusted in https://github.com/sourcegraph/sourcegraph/pull/37536#discussion_r905931022) and other potentially useful numeric primitives.
The linked comment also comments on the weight of making these changes - my thoughts:
- We want to make sure we shim everything, because we inject some custom behaviour (notably with the log.Error field), and we want to make sure nobody uses zap.Any, so I think this overhead is _worthwhile_
- I think we're pretty close to covering all the most frequently used fields - we've only had 2 requests for new fields to date (this one, and https://github.com/sourcegraph/log/pull/7), so I think this is a _manageable_ overhead as well
> fields: add Binary, missing numeric fields

- internal/sinkcores/sentrycore/core.go
- internal/sinkcores/sentrycore/doc.go
- internal/sinkcores/sentrycore/integration_test.go
- internal/sinkcores/sentrycore/worker.go
After taking another look at our Sentry reports, the good news is that most of the errors sent with a warning level are indeed transient. The bad news is we can't really filter those out automatically and to be frank it doesn't make much sense to do so. 
The value of an error on Sentry is that it's a useful signal and transient errors are not fitting that case that much. 
I originally kept those in when writing this code because I was curious to see what kind of transient errors we were reporting. 
So at this point, I think it's better to simply stop getting those reported. Using metrics to track how those errors are evolving is a much better signal and will create much less noise. 
Were we to decide otherwise and to make this togglable, it's just a revert away on this PR. I went against …
> Only send to Sentry logs on Error level and above

- fields.go
- go.mod
- logger_test.go
Reverts sourcegraph/log#14
IMO we should just use `StringPtr`, `IntPtr`, etc for clarity and API consistency, and avoid using what is effectively an equivalent of `zap.Any` - my generic idea was somewhat miscommunicated, and the actual intent of that idea turns out to not be a great idea, so we should just go with the perhaps verbose but arguably more correct way of doing things. See discussion in https://github.com/sourcegraph/log/pull/15
> Revert "Export a log.StringPtr function to safely log *string "

- internal/sinkcores/sentrycore/default_sentry_client_opts.go
- sinks_sentry.go
- sinks_sentry_test.go
I went for keeping the ability to pass sentry client options directly rather than taking in an env var as it's kind of confusing to have an external module automatically reading env var. 
This sets the default sampling rate to 10%, which should be largely enough for our usage. As it's now a default, we'll be able to remove the configuring code that's present in the main funcs of every service.
> Add overridable default sentry client options

- init.go
- internal/globallogger/globallogger.go
- logger.go
- logger_test.go
The desired behaviour is:
- in dev, panic if `Scoped` comes before `Init`
- in prod, use a no-op logger if `Scoped` comes before `Init`
Right now it seems the first behaviour never occurs:
- at initialization: `globallogger.devMode = false`
- at illegal `log.Scoped`: devmode is false, return no-op
- at `log.Init`: devmode = true
This means illegal `log.Scoped` usages are never caught. After this change, we catch some illegal logger instantiations:
Pretty serious oversight unfortunately 😬 I've found quite a lot of illegal logger initializations we'll need to fix, but for now this we're safe - it just means some logging is silently being discarded without us knowing.
> log: fix devmode and safe logger instantiation

- init.go
- internal/encoders/encoders.go
- internal/globallogger/globallogger.go
- internal/otelfields/otelfields.go
- internal/sinkcores/sentrycore/integration_test.go
- internal/sinkcores/sentrycore/worker.go
- logger.go
- logger_test.go
- logtest/logtest.go
ot = opentracing, otel = opentelemetry - similar to https://github.com/sourcegraph/sourcegraph/pull/39464
> otelfields: make package private, rename to otelfields

- internal/sinkcores/sentrycore/default_sentry_client_opts.go
- sinks_sentry.go
This removes the auto merged of default values into the provided client options. Sometimes you really want to set certain values and don't want defaults applied.
If users want defaults, the no arg constructor uses `DefaultSentryClientOptions`.
> remove merge of default client opts

- internal/globallogger/globallogger.go
zapcore v1.22 added `WithFatalHook` which allows one to execute some custom code after a Fatal log. We add a forceSyncer which force calls Sync on the underlying core before halting execution as per the advice from https://pkg.go.dev/go.uber.org/zap#WithFatalHook
Manual testing
> add forceSyncer on log inititalization to force Sync cores

- logger.go
If tracing is disabled, we don't want to explicitly spam with empty TraceContexts.
> logger: no-op if WithTrace is provided an empty TraceContext

- logger.go
- logtest/logtest.go
Adding as part of investigations into how we can introduce #28 safely into `sourcegraph/sourcegraph`. Some parts of the codebase (`TestContext`) really needs a truly no-op logger that can be provided before initialization, so we added a `NoOp` constructor and hope it does not get misused.
> log: add a native NoOp logger

- init.go
- internal/globallogger/globallogger.go
- logger.go
- logger_test.go
This reverts commit e94dc0c4d111999b24c0649e5a33ffd38cb3748f.
This re-applies https://github.com/sourcegraph/log/pull/24
> re-apply "#24: log: fix devmode and safe logger instantiation"

- logger.go
- logger_test.go
Adds documentation indicating that WithTrace can safely be called repeatedly, and adds a test validating this behaviour.
Prompted by discussion here: https://github.com/sourcegraph/sourcegraph/pull/41345#issuecomment-1238335748
> logger: validate that WithTrace can be called repeatedly

- internal/sinkcores/sentrycore/worker.go
In the cla-bot sync tool I want to use `instance.id` as a tag to indicate the workflow run, but right now they are only treated as extra attributes. This adds all the resource fields as tags _if_ they are set.
> sentrycore: support all resource tags

- init.go
- internal/sinkcores/outputcore/core.go
- internal/sinkcores/outputcore/override.go
- logtest/logtest.go
- sinks_output.go
- sinks_output_test.go
SRC_LOG_SCOPE_LEVEL allows operators to override the log level for
specific loggers and there children. It is an comma seperated
environment variable which takes a logger name and level. If a log
message matches the logger name (or a parent of it does) AND the log
level allows it then it will always be logged. A parent is defined by
how we join scoped loggers with a ".".
The motivation for this is in production we log with very low verbosity,
but when testing a feature it can be useful to turn up the verbosity for
specific logs. For example while I was developing hybrid searcher it
would of been great to make just that debug, but avoid debug for
everything else due to the noise.
Test Plan: Added unit tests which test from the envar level.
> introduce SRC_LOG_SCOPE_LEVEL

- sinks_output_test.go
Minor bug I just noticed. The unsetenv test helper needs to reset they process level environment variable, but using t.Setenv won't have that effect since it will just be cleaned up straight away.
Test Plan: go test
> use os.Setenv in unsetenv test helper

- cmd/example/main.go
- internal/sinkcores/outputcore/core.go
- logtest/logtest.go
- sinks_output.go
`encoders.BuildEncoder` relies on the `development bool` argument to assess whether to apply our dev config for easier-to-read output. It looks like we no longer call `BuildEncoder` with anything except `development: false` - I don't recall what it used to be, but setting it to `globallogger.DevMode()` should fix it. We can't place this in `BuildEncoder` itself because that would cause an import cycle between package `encoders` and `globallogger`.
Since we have `(*outputSink).development` available, however, I've opted to prop-drill it in to `NewCore` from the top-level variable. `development` is a bit problematic to work with - we might want to better refactor the interactions here at some point.
Test plan: I added a sanity-check program, `cmd/example`, to do some quick-and-easy visual …
> outputcore: correctly use dev mode to apply configuration

- logr/go.mod
The submodule's `go.mod` is currently invalid - not sure how this happened, but the `replace` made it go unnoticed
> logr: stub a valid sourcegraph/log revision

- logr/logger.go
- logr/logger_test.go
- logr/logr.go
Allows us to retrieve a preconfigured log.Logger from a preconfigured logr.Logger, which is provided to us in kubebuilder handlers.
> logr: add a way to get the underlying log.Logger

- logtest/logtest.go
- logtest/logtest_test.go
Finding a particular entry or set of entries is a pretty common assertion - in #55 I added a slice type `CapturedLogs`, which can become a home for some simple utilities to help with asserting particular entries get logged.
> logtest: add Filter, Contains on CapturedLogs

- internal/sinkcores/sentrycore/integration_test.go
- internal/sinkcores/sentrycore/worker.go
- sinks.go
Sentry has some fancy features around version tracking, environments, and whatnot - this change propagates relevant fields from the resource we initialize everything with onto events so that we might be able to take advantage of it.
> sentrycore: add first-class metadata from resource

- sinks_sentry.go
Right now, removing Sentry config doesn't disable it because we return immediately here.
> sentrycore: disable if sentry config is nil

- internal/sinkcores/sentrycore/worker.go
Every once in a while an unhelpfully formatted error shows up in our Sentry reporting:
After digging into this because it bothers me, turns out that even though the Sentry library says "first" exception is used for the title it actually uses the last one! Sure enough, this is mentioned in the cockroach error source:
https://github.com/cockroachdb/errors/blob/26622367a22260fa287d2f7aa2a085b0324c74ee/report/report.go#L324-L325
and we see it in action in the Sentry UI, the title is the exception we _don't_ overwrite when there are multiple:
Another example: https://sourcegraph.sentry.io/issues/4193949796/?project=6583153
The errors where the title is what we want all have only 1 generated exception.
I originally thought that maybe we should overwrite each detected exception individually with …
> sentrycore: set generated exceptionType on last exception instead of the first

- init.go
- internal/encoders/config.go
- output/output.go
When deploying a service that sends out logs to cloud logging, the severity was not parsed and because logs of our services are all sent out of STDERR, they all defaulted to `severity: "ERROR"`, making it quite hard to read. 
This PRs adds a new `SRC_LOG_FORMAT=json_gcp`, which outputs json logs in a structure that cloud logging understands. 
See the results of a little test in Cloud run:
> Add a new format, `JSON_GCP`

- logger.go
This was added early on to show descriptions of log scopes somewhere. It's pretty useless, and noisy - let's just get rid of it
aside: the scope description parameter in general is pretty useless as well, maybe someone can do the honors of getting rid of that as well :)
> logger: remove log scope debug message

- cmd/example/main.go
- init.go
- internal/configurable/logger_test.go
- internal/sinkcores/sentrycore/integration_test.go
- logger.go
- logtest/logtest.go
- sinks.go
As the great @bobheadxi once upon a time said
> aside: the scope description parameter in general is pretty useless as well, maybe someone can do the honors of getting rid of that as well :)
- Robert, circa 2023 [PR](https://github.com/sourcegraph/log/pull/62)
Related:
- https://github.com/sourcegraph/sourcegraph/pull/57690
- https://github.com/sourcegraph/zoekt/pull/657
- https://github.com/sourcegraph/mountinfo/pull/5
> remove description

- internal/sinkcores/sentrycore/integration_test.go
- internal/sinkcores/sentrycore/worker.go
Following https://develop.sentry.dev/sdk/event-payloads/contexts/#trace-context - looks like Sentry might have some special UI presentation/categorization capabilities around this
> sentrycore: emit trace ID, span ID in Sentry-specific trace context as well

- init.go
- internal/sinkcores/outputcore/override.go
- sinks_output_test.go
As per our discussion in [slack](https://sourcegraph.slack.com/archives/C04MYFW01NV/p1741728615123969), I think it would be nice to allow override logs to raise the level of severity. To that end, my proposed changes are:
* Always return an override core if overrides are provided
* Check overrides first in override core, and then fall back to base levels
I acknowledge this does introduce a performance hit when SRC_LOG_SCOPE_LEVEL is defined, but I doubt it's significant. If we're concerned, I could put this behavior behind an env var like SRC_LOG_OVERRIDES_CAN_INCREASE_SEVERITY (not the punchiest, but gets the point across). However, I'd personally prefer if it was the default because I was surprised by the current behavior and clearly thought it was a bug.
Updated and added unit test …
> feat(overrides): updated overrideCore to allow filtering out logs at a higher level
